name: Prerelease

on:
  create:
    tags:
      - 'prerelease-*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: '${{ secrets.TOLGEE_MACHINE_PAT }}'

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: npm install -g npm@7

      - name: Install
        run: npm run ci:init

      - name: Update version locally
        run: lerna version --no-push --conventional-commits --conventional-prerelease --no-changelog --preid $(git rev-parse HEAD)

      # Set TOLGEE_UI_VERSION for @tolgee/core build
      - name: Set env
        run: echo "TOLGEE_UI_VERSION=$(npm run --silent ui-version)" >> $GITHUB_ENV

      - name: Build all packages
        run: npm run ci:build

      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: lerna publish from-package --yes

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress
          path: |
            cypress/videos/**/*
            cypress/screenshots/**/*
