name: Prerelease

on:
  push:
    tags:
      - 'prerelease'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.TOLGEE_MACHINE_PAT }}'

      - run: git checkout -b branch-prerelease-${{ github.sha }}

      - name: Set git globals
        run: |
          git config --local user.email "machine@tolgee.io"
          git config --local user.name "Tolgee Machine"

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: npm install -g npm@7

      - name: Install
        run: npm run ci:init

      - name: Update version locally
        run: lerna version --yes --no-push --conventional-commits --conventional-prerelease --no-changelog --preid prerelease-${{ github.sha }}

      # Set TOLGEE_UI_VERSION for @tolgee/core build
      - name: Set env
        run: echo "TOLGEE_UI_VERSION=$(npm run --silent ui-version)" >> $GITHUB_ENV

      - name: Build all packages
        run: npm run ci:build

      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push to git
        run: git push --follow-tags -u origin $(git rev-parse --abbrev-ref HEAD)

      - name: Publish
        run: lerna publish from-package --yes

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress
          path: |
            cypress/videos/**/*
            cypress/screenshots/**/*
